name: threads
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  form_validator: ^2.1.1
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.8.3
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  uuid: ^3.0.4
  jiffy: ^6.3.2
  lottie: ^3.3.1

  animated_splash_screen: ^1.3.0
  icons_launcher: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - assets/animations/

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
